
#
# This external dependency pulls MU_BASECORE for the Config feature package CI.
# This should not be pulled when consuming this package as a dependency.
#
{
  "scope": "global",
  "type": "git",
  "name": "FEATURE_CONFIG",
  "var_name": "FEATURE_CONFIG_PATH",
  "source": "https://github.com/microsoft/mu_feature_config.git",
  "version": "aedb83bef7882353b3ee36958f23df65468db3eb",
  "flags": ["set_build_var"]
}
